name: Java CI and Deploy to Render

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Récupérer le code
      - uses: actions/checkout@v3

      # 2) Installer Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3) Build Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # 4) Construire l'image Docker
      - name: Build Docker image
        run: docker build -t my-app .

      # 5) Déployer sur Render
      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.srv-d4io0p49c44c73b0n32g }}
          api-key: ${{ secrets.githubrender }}
